<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todoparentobject</name>
   <tag></tag>
   <elementGuidId>55760390-2534-43a2-a04b-7dcff2ab6630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(text(),'${value}')]/parent::div/parent::li[@class='${value1}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(text(),'${value}')]/parent::div/parent::li[@class='${value1}']</value>
   </webElementProperties>
</WebElementEntity>
