<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo_checkbox</name>
   <tag></tag>
   <elementGuidId>c06f56f9-8ffe-4e60-a4a8-5ff7474d1668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;todo-list&quot;]//input[@class='toggle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;todo-list&quot;]//input[@class='toggle']</value>
   </webElementProperties>
</WebElementEntity>
