<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo-list</name>
   <tag></tag>
   <elementGuidId>371870b5-768f-4880-9539-c6be20f56abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;todo-list&quot;]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;todo-list&quot;]/li</value>
   </webElementProperties>
</WebElementEntity>
