<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo-list1</name>
   <tag></tag>
   <elementGuidId>8e4ccef3-99aa-4444-a807-dad5d10183d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;todo-list&quot;]/li[@class=&quot;${value}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;todo-list&quot;]/li[@class=&quot;${value}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
